"""empty message

Revision ID: 3b44c9d18ed4
Revises: 
Create Date: 2017-07-19 16:30:33.518322

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from users.models import User

# revision identifiers, used by Alembic.
revision = '3b44c9d18ed4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('role', sqlalchemy_utils.types.choice.ChoiceType(User.USER_ROLE), nullable=True),
    sa.Column('password', sqlalchemy_utils.types.password.PasswordType(
        schemes=[
            'pbkdf2_sha512',
            'md5_crypt'
        ],
        deprecated=['md5_crypt']
    ), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
